import { PlanetClass, type Planet } from "@types"

export const planets: Planet[] = [
    {
        id: "trappist-1b",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 7110,
        distance: 1720000,
        color: "#a48074",
        axis: 12,
        orbit_duration: 1.51,
        rotate_duration: 1.51,
        texture: "trappist-1_b.png",
        icon: "earth.png",
        satellites: []
    },
    {
        id: "trappist-1c",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 6989,
        distance: 2360000,
        color: "#c2a98f",
        axis: -5,
        orbit_duration: 2.42,
        rotate_duration: 2.42,
        texture: "trappist-1_c.png",
        icon: "earth.png",
        satellites: []
    },
    {
        id: "trappist-1d",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 5020,
        distance: 3340000,
        color: "#6c89a0",
        axis: 6,
        orbit_duration: 4.05,
        rotate_duration: 4.05,
        texture: "trappist-1_d.png",
        cloud_texture: "trappist-1_d_cloud.png",
        icon: "earth.png",
        satellites: []
    },
    {
        id: "trappist-1e",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 5861,
        distance: 4380000,
        color: "#839c91",
        axis: -17,
        orbit_duration: 6.10,
        rotate_duration: 6.10,
        texture: "trappist-1_e.png",
        cloud_texture: "trappist-1_e_cloud.png",
        icon: "earth.png",
        satellites: []
    },
    {
        id: "trappist-1f",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 6657,
        distance: 5760000,
        color: "#99b3b8",
        axis: 21,
        orbit_duration: 9.21,
        rotate_duration: 9.21,
        texture: "trappist-1_f.png",
        cloud_texture: "trappist-1_f_cloud.png",
        icon: "earth.png",
        satellites: []
    },
    {
        id: "trappist-1g",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 7192,
        distance: 7020000,
        color: "#7fa699",
        axis: -3,
        orbit_duration: 12.35,
        rotate_duration: 12.35,
        texture: "trappist-1_g.png",
        cloud_texture: "trappist-1_g_cloud.png",
        icon: "earth.png",
        satellites: []
    },
    {
        id: "trappist-1h",
        type: "planet",
        class: PlanetClass.Terrestrial,
        parent: "trappist-1",
        radius: 4810,
        distance: 9260000,
        color: "#c0c0c0",
        axis: 14,
        orbit_duration: 18.77,
        rotate_duration: 18.77,
        texture: "trappist-1_h.png",
        icon: "earth.png",
        satellites: []
    }
]
